### ISSUE TITLE
All components of the same type must be positioned differently

### ISSUE THREAD

**Issue by alexeiva** [m4rc1e/mf-glyphs-scripts#12]
@m4rc1e could you clarify what this means?

```
ERROR: glyph endash layer Regular: 2 components of hyphen share 1 transformations.
    All components of the same type must be positioned differently.

ERROR: glyph endash layer Bold: 2 components of hyphen share 1 transformations.
    All components of the same type must be positioned differently.
```

In Inconsolata `softhyphen` and `hyphentwo` share the same component. 

BTW Regarding `softhyphen` — I prefer to leave it empty — what is your take?

<img width="537" alt="screen shot 2016-09-23 at 12 53 33" src="https://cloud.githubusercontent.com/assets/16634089/18783590/de5f4e50-818c-11e6-9987-17cd560449f5.png">

<img width="573" alt="screen shot 2016-09-23 at 12 53 35" src="https://cloud.githubusercontent.com/assets/16634089/18783592/e1c5630e-818c-11e6-9b01-c1a5905f3ed6.png">

**Comment by graphicore** [comment]
It means there are two components of `hyphen` in each layer `Regular` and `Bold` but you don't see it because they are positioned exactly on top of each other (share the same transformation)

**Comment by alexeiva** [comment]
So why is it a problem, and how can it be fixed?

**Comment by graphicore** [comment]
> So why is it a problem

First of all, its redundant. Also, it's a strong hint for a mistake, e.g. this happens when Glyphs generates a glyph like `quotedblright`. The quoteright is inserted twice at the same position, the designer doesn't touch it anymore and  `quotedblright` ends up broken.

In this case, I don't know why it happened. Is there  a good reason for it? We may have to think about the test,

> and how can it be fixed?

Go into layer `Regular` and delete one of the two references to `hyphen`. Go into layer `Bold` and delete one of the two references to `hyphen`.

**Comment by graphicore** [comment]
@alexeiva did it work?

**Comment by alexeiva** [comment]
@graphicore thank you for the explanation. If I break the component in `softhyphen` it passes the QA fine. 

About the `softhyphen` there are 2 conventions for this glyph.  I prefer the second variant — the [invisible softhyphen](https://en.wikipedia.org/wiki/Soft_hyphen). It is a more practical and popular application. But the QA script won't let me. 

<img width="813" alt="screen shot 2016-09-28 at 19 47 19" src="https://cloud.githubusercontent.com/assets/16634089/18925500/7bf16b78-85b4-11e6-9a13-8bae93c4071a.png">

<img width="719" alt="screen shot 2016-09-28 at 19 47 06" src="https://cloud.githubusercontent.com/assets/16634089/18925545/a6e75518-85b4-11e6-994b-d1bf005d08c8.png">

<img width="721" alt="screen shot 2016-09-28 at 19 46 40" src="https://cloud.githubusercontent.com/assets/16634089/18925553/afd61d9e-85b4-11e6-9774-e3f6e84bb8e3.png">

<img width="720" alt="screen shot 2016-09-28 at 19 46 29" src="https://cloud.githubusercontent.com/assets/16634089/18925579/c86e00ba-85b4-11e6-8333-bf464c60f097.png">

<img width="726" alt="screen shot 2016-09-28 at 19 50 28" src="https://cloud.githubusercontent.com/assets/16634089/18925593/d49cff6c-85b4-11e6-9c74-858f74327be1.png">

**Comment by graphicore** [comment]
> If I break the component in softhyphen it passes the QA fine.

Hmm, doesn't sound like what I said.

> About the softhyphen there are 2 conventions for this glyph … But the QA script won't let me. 

How do you implement it? And what the QA script output?

**Comment by alexeiva** [comment]
> How do you implement it? And what the QA script output?

Simply an empty glyph. In case of monospaced Inconsolata with the standard 500 width.

<img width="444" alt="screen shot 2016-09-28 at 19 58 36" src="https://cloud.githubusercontent.com/assets/16634089/18925970/4994383e-85b6-11e6-82ea-361f76e906d3.png">
<img width="276" alt="screen shot 2016-09-28 at 19 58 23" src="https://cloud.githubusercontent.com/assets/16634089/18925969/499167c6-85b6-11e6-89e8-6bc7fb99ba21.png">


This is what I get
```
ERROR: Regular master's softhyphen should have outlines or components
ERROR: Bold master's softhyphen should have outlines or components
```

However, I am probably mistaken. 
Just checked PT Sans:

<img width="397" alt="screen shot 2016-09-28 at 20 04 15" src="https://cloud.githubusercontent.com/assets/16634089/18926126/e5b6a5bc-85b6-11e6-8c1e-8dcab654d72d.png">

Technically this glyph has outlines, but it appears invisible in running text, and becomes a hyphen in case of a word-wrap.

So I will simply follow this convention.

**Comment by graphicore** [comment]
Probably the text layout engine is pulling that trick.
