### ISSUE TITLE
fsType check in QA broke?

### ISSUE THREAD

**Issue by alexeiva** [m4rc1e/mf-glyphs-scripts#13]
1. Ran QA script on https://github.com/alexeiva/YesevaOne/commit/ceffb7d91cfba04bf7172af80969ee2a9ec3b6ea

2. Result
fstype=installable exists in FontInfo, but script doesn't see it, and produces error
<img width="710" alt="screen shot 2016-09-23 at 21 00 29" src="https://cloud.githubusercontent.com/assets/16634089/18798038/e026fae6-81d0-11e6-916f-284d197b08c3.png">

**Comment by m4rc1e** [comment]
@alexeiva this has been fixed in c70d58b

Dave started a convo on the [glyphsapp forum](https://forum.glyphsapp.com/t/fstype-ui-confusing/4524/2)

Sorry for the delay.

**Comment by alexeiva** [comment]
Since fsType is now NULL, it creates an error

`ERROR YML DOC: Attribute fsType does not exist for font`

Can you update the script to make an exception for this?
```
    print '***Check Meta Data***'
    for key in qa_spec:
        font_attrib = fontinfo.font_field(font, key)
        if font_attrib:
            fontinfo.check_field(key, qa_spec[key], font_attrib)
        else:
            print ('ERROR YML DOC: Attribute %s does not exist for font\n' % key)
```

**Comment by m4rc1e** [comment]
Sure!

Thank you
