### ISSUE TITLE
[Error] QA Script

### ISSUE THREAD

**Issue by kalapi** [m4rc1e/mf-glyphs-scripts#14]
Hi Marc, 

I'm getting this error when I try to run the script. I haven't looked into the python script yet.

<img width="532" alt="screen shot 2016-09-28 at 10 06 02 am" src="https://cloud.githubusercontent.com/assets/15804460/18901134/f01d9bb0-8565-11e6-9782-217e4721c929.png">

Let me know if i'm doing anything wrong.
Thanks!
K

**Comment by m4rc1e** [comment]
Which repo?

**Comment by kalapi** [comment]
@m4rc1e Ah shit sorry. I thought I mentioned the specifics.

Script Name: `checkfamily.py`
GlyphsApp Version: `Version 2.3 (895)`

**Comment by m4rc1e** [comment]
Could you update to 2.4b (924)

I'm very sorry for the delay in replying.
