### ISSUE TITLE
noBreak and nonmarkingreturn

### ISSUE THREAD

**Issue by alexeiva** [m4rc1e/mf-glyphs-scripts#15]
What is best practice for glyphs `nonmarkingreturn`, and `noBreak`?

```
ERROR: Regular master's nonmarkingreturn should have outlines or components
ERROR: Bold master's noBreak should have outlines or components
```

Should we include them in all GF fonts?

**Comment by alexeiva** [comment]
Can the "no glyph—no problem" principle be applied?

**Comment by m4rc1e** [comment]
nonmarkingreturn isn't that meant to be CR?

**Comment by alexeiva** [comment]
I just removed these glyphs, and it fixed the issue. Must have been some obsolete naming scheme.
