### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by crystaltype** [m4rc1e/mf-glyphs-scripts#17]
When I run the check vertical metrics using Khaled's approach in some glyphs file it gives this error:

***Instances share same vertical metrics***
Traceback (most recent call last):
  File "test_khaled_metrics.py", line 167, in <module>
    main_glyphsapp()
  File "test_khaled_metrics.py", line 140, in main_glyphsapp
    consistent_vert_instances = vert_metrics_match(font)
  File "test_khaled_metrics.py", line 108, in vert_metrics_match
    master_metrics[i][key] = float(master.customParameters[key])
TypeError: float() argument must be a string or a number
End

**Comment by crystaltype** [comment]
oh and I tried reset glyphs app but it still gives this error. It only occurred in some glyphs file tho

**Comment by m4rc1e** [comment]
@crystaltype could you send me a link to the repo please?

I need to make this error message more clear. It occurs when some of the vertical metrics fields are missing.

I'll make this error message clearer.

**Comment by m4rc1e** [comment]
@crystaltype ok, found the problem. No need for the repo link.

I'll update the scripts.

Cheers
Marc

**Comment by m4rc1e** [comment]
Ok, this should be fixed in the latest commit, 8949f8a.

Output now looks like this.

![screen shot 2016-09-30 at 20 42 49](https://cloud.githubusercontent.com/assets/7525512/19002932/b67f9986-874e-11e6-90eb-19236b2d2e63.png)
