### ISSUE TITLE
nasty naming issue

### ISSUE THREAD

**Issue by alexeiva** [m4rc1e/mf-glyphs-scripts#20]
The `fix GF specs` script does this nasty little thing to my shiny new style linking

![screen shot 2016-10-15 at 12 27 19](https://cloud.githubusercontent.com/assets/16634089/19412883/17a45e5a-92d4-11e6-8f4d-b9b1783ec7c3.png)

This in turn creates an autrocious fontbakery error!
```
ERROR    [FONT_FAMILY_NAME(1):WINDOWS(3)] entry: expected 'Scada' but got 'Scada Bold' 
```

This sucks! :-) [  &copy; @davelab6 ]

**Comment by m4rc1e** [comment]
I'm on it like Sonic.

**Comment by m4rc1e** [comment]
Ok can confirm this is legit.

I will get a fix sorted asap.

Thanks

**Comment by m4rc1e** [comment]
Hey,

This should be fixed in 0e7e19b. this will not fix repositories which already have this problem.

The field needs to be removed by hand or I can write a quite patch script.

**Comment by alexeiva** [comment]
Tried your script on a 3 style fonts. Did not work. 
Can you take a look?

https://github.com/alexeiva/Comfortaa/tree/1f196336f17ab7dc45e07b5f1d9c244128068e6e/sources

**Comment by alexeiva** [comment]
never mind. was my fault. I did not set bold=700 in the bold instance. It was 400 instead. Now works like a charm 
thank you!

**Comment by davelab6** [comment]
Good job guys
