### ISSUE TITLE
Vietnamese accents set up correctly?

### ISSUE THREAD

**Issue by davelab6** [m4rc1e/mf-glyphs-scripts#25]
Following https://github.com/google/fonts/pull/555 I wonder if you can add to your glyphs checking script a way to notify if the Vietnamese glyphs have been set up in the preferred way, as there are several ways to make Viet glyphs and only 1 is preferred.

**Comment by alexeiva** [comment]
I would say using `acutecomb.loclVIT` is an exceptional edge-case but not general practice.

@impallari and @crystaltype had a debate on common Latin and Vietnamese accents In Libre Franklin, for which this solution was proposed.

**Comment by m4rc1e** [comment]
@davelab6 @alexeiva 

this has been added in commit 9db2878, https://github.com/m4rc1e/mf-glyphs-scripts/blob/master/QA/otfeatures.py#L68-L81.
