### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kontur** [m4rc1e/mf-glyphs-scripts#30]
Since the project has no explicit license info one has to assume it copyrighted, i.e. not available to make derivatives. 

Is this your intention, or are you actually welcoming remixes? In the latter case a license file would be great to add.

**Comment by m4rc1e** [comment]
Thanks @kontur.

I've always believed everyone can do what they want with these scripts. They're not particularly elegant but I'm glad folks are finding them useful. With this in mind, I've decided to MIT license this project.

https://github.com/m4rc1e/mf-glyphs-scripts/commit/c5ed026e5b72a886f1e574f85659cdcae041e66a
