### ISSUE TITLE
[Test repo matches gf-checklist structure]

### ISSUE THREAD

**Issue by kalapi** [m4rc1e/mf-glyphs-scripts#4]
Hi Marc, 

I have fstype set to installable but I get the respective error regardless (image below).

<img width="1079" alt="screen shot 2016-08-12 at 1 50 08 pm" src="https://cloud.githubusercontent.com/assets/15804460/17616765/ec588a86-6093-11e6-9e1d-9457409a1c4c.png">

You can test the .glyphs source in question here -> https://github.com/kalapi/Montserrat

Many thanks!

**Comment by m4rc1e** [comment]
Hey Kalapi, 

Before Glyphsapp 2.3.1. I couldn't set and check the fsType via the python api property. This has now been sorted in the latest release. Hence why I set the message to 'ERROR in Glyphsapp'. I will update this so it checks now.

Thanks

**Comment by kalapi** [comment]
Thanks for the clarification! I couldn't decode 'ERROR in Glyphsapp'. Maybe you could say 'not implemented in Glyphsapp' or 'Glyphsapp Bug'?

**Comment by m4rc1e** [comment]
This will be sorted over the weekend. 

I am collating the individual scripts and making a universal QA script with vanilla dialogs.
