### ISSUE TITLE
Installing yaml help

### ISSUE THREAD

**Issue by impallari** [m4rc1e/mf-glyphs-scripts#7]
Hi Mark, please as some help in the Readme.md about installing yaml, since its required by some of your scripts, and is not installed by default in all computers.

I tried to install it, but was unsure which one to pick, since there are 3 option available: 
- PyYAML        # YAML 1.1, pure python and libyaml binding
- ruamel.yaml   # YAML 1.2, update of PyYAML with round-tripping of comments
- PySyck        # YAML 1.0, syck binding

**Comment by graphicore** [comment]
It's `pip install pyyaml`.

**Comment by impallari** [comment]
pip: command not found :)

**Comment by graphicore** [comment]
haha!

Either `sudo easy_install pip` or, probably more straight forward `sudo easy_install pyyaml`.

I think the easy_install is going in your mac root and pip is installing just for your user. Also, I never tried the latter easy_install command.

**Comment by impallari** [comment]
Thanks Lase!
sudo easy_install => error: No urls, filenames, or requirements specified (see --help)
sudo easy_install pyyaml => Installed!

**Comment by m4rc1e** [comment]
Hey folks,

Oh jeez, there I was thinking pyaml was 'batteries included'. This raises and interesting point. The majority of people who will use this tool will not understand Python dependencies such as easy_install or pip. It will make everyone's lives easier if we only use the Python standard library. I also don't like polluting my system Python etc... or this happens ;)

I will think of something but this is a very good issue. Thanks Pablo

**Comment by graphicore** [comment]
just use json?

**Comment by m4rc1e** [comment]
Right commit 08ebb23 now uses json.
