### ISSUE TITLE
GF Check Fonts

### ISSUE THREAD

**Issue by impallari** [m4rc1e/mf-glyphs-scripts#9]
I get this error:
```
Start
Traceback (most recent call last):
  File "checkfamily.py", line 18, in <module>
    script_path = glob.glob(r'/Users/*/Library/Application Support/Glyphs/Scripts/mf-glyphs-scripts')[0]
IndexError: list index out of range
End
```

**Comment by m4rc1e** [comment]
Are you copying and pasting the scripts into the macro window?

The scripts have to be installed into the Glyphsapp script folder.

Your Glyphsapp scripts folder path should be the following:
/Users/your-username/Library/Application Support/Glyphs/Scripts.

Could you paste the location of your Glyphsapp scripts folder please?

glob.glob is like regex for retrieving paths.

Cheers,
Marc

**Comment by impallari** [comment]
They are properly installed inside the Glyphs script folder,  but inside a "MarckFolei" folder, instead of the default "mf-glyphs-scripts"

**Comment by graphicore** [comment]
Marc, you actually don't have to use glob, you can also do something like [here](https://github.com/graphicore/Glyphs-Scripts/blob/master/Paths/Correct%20Path%20Directions%20All%20Layers.py#L9)

```py
import sys, os
parentDir = os.path.abspath('..')
if parentDir not in sys.path:
    sys.path.insert(0, parentDir)
```
The advantage is that you make one less assumption about where the `Glyphs/Script` directory is located.

**Comment by m4rc1e** [comment]
@impallari That explains everything ;)

@graphicore there is another issue by doing it your way. I'll write this up tomorrow.

**Comment by graphicore** [comment]
I got my way from the Glyphs forum.

**Comment by m4rc1e** [comment]
@graphicore yep, worked a charm.

Updated in e511928

closed

**Comment by alexeiva** [comment]
Just updated the script from e511928.
Here is the error I get:

```
Start
Traceback (most recent call last):
  File "checkfamily.py", line 19, in <module>
    from QA import (
ImportError: No module named QA
End

```

<img width="895" alt="screen shot 2016-08-30 at 13 30 51" src="https://cloud.githubusercontent.com/assets/16634089/18085924/0306f49a-6eb6-11e6-980f-93dcafa3400d.png">

**Comment by alexeiva** [comment]
So what dependency should I install for the QA module?

**Comment by m4rc1e** [comment]
Hey Alexei,

in glyphs, close all fonts. Then type this into the macro window/

```
import os
print os.path.abspath('..')
```

What do you get?

**Comment by alexeiva** [comment]
I get:
`/`

**Comment by m4rc1e** [comment]
Does your version of checkfamily.py have:

```
script_path = os.path.abspath('..')
if script_path not in sys.path:
    sys.path.append(script_path)
from QA import (
    glyphs,
    fontinfo,
    metrics,
)
```

**Comment by m4rc1e** [comment]
ahhh, I found the issue.

missing __init__.pyc

**Comment by m4rc1e** [comment]
Ok, I've updated.

Repull the repo and try again please.

**Comment by alexeiva** [comment]
Works now. Thank you!

**Comment by alexeiva** [comment]
After running `fix fonts for GF spec script` on https://github.com/alexeiva/YesevaOne/commit/28c4adb11c11c450eca9ac81fd3796ed91c06de9

The QA script produces this error. Before all was okay.

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "checkfamily.py", line 77, in buttonCallback
    main(**self.w.__dict__)
TypeError: main() takes no arguments (24 given)
```

**Comment by alexeiva** [comment]
Nevermind. The issue disappeared after restarting Glyphs

**Comment by alexeiva** [comment]
I keep getting this error every second time I run check Font.

Any ideas what the cluster is all about?

```
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/vanilla/vanillaBase.py", line 196, in action_
    self.callback(sender)
  File "checkfamily.py", line 83, in buttonCallback
    main(**self.w.__dict__)
TypeError: main() takes no arguments (28 given)
```
